#!/bin/sh
export NO_CUSTOM_KEYS=1

repo=$(pwd)
cd ~/dev/contribs/qtile/

./scripts/ffibuild

rm -f $repo/images/*.png > /dev/null 2>&1
./scripts/gen-keybinding-img -c $repo/config.py -o $repo/images/

